### ISSUE TITLE
Make gdi-userportal-docs FOSS license compliant

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-docs#5]
## What
Add `CONTRIBUTING.MD`
Add `CODE_OF_CONDUCT.md`.

## Why
To be FOSS license compliant.

**Comment by hallundbaek** [comment]
I've tried to look for some low overhead examples as a starting-off point for `CONTRIBUTING.md`, though most are naturally geared towards code.

https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md seems to be a good starting point, if we want to start almost from scratch, another option would be to use https://generator.contributing.md/, it has a lot more sections that are already filled out and that would need to be adapted instead of written from scratch.

For the  `CODE_OF_CONDUCT.md` we could adopt the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) which has [quite a lot of prominent adopters.](https://www.contributor-covenant.org/adopters/)

**Comment by brunopacheco1** [comment]
@hallundbaek Thanks for your suggestions. I will generate the `CONTRIBUTING.md` and reuse `CODE_OF_CONDUCT.md` from `Contributor Covenant Code of Conduct`.
